### ISSUE TITLE
Shader Documentation

### ISSUE THREAD

**Issue by my-little-bunny** [lachlanmcdonald/magicavoxel-shaders#21]
Hi there, I've been using your shaders for a very long time now, and in the past your readme pages had info with test command examples. 

I'm looking at the case shader at the moment, and there's no text explaining how to add an axis argument — I've tried `xs case x 12`, `xs case 12 x`, `xs case xy 12`, etc. The shader panel only has colour options and doesn't have axes to choose from.

I even used wayback archive to access your older instructions, and it seems they never actually explained how to target axes.

Could you be so kind to:
1. Explain how do I make the shader work with an axis argument.
2. Bring back short commands overview so it would be easier to understand how to use a shader?

Thank you so much in advance.

**Comment by lachlanmcdonald** [comment]
Hi @my-little-bunny, the axis mode is set in the brush panel. 

![Screenshot 2020-12-09 at 10 37 54](https://user-images.githubusercontent.com/1478362/101619238-e91ce100-3a0a-11eb-9b67-b047ad3c58ee.png)

Whatever mode is set will be incorporated into the shader.

In the recent versions of MagicaVoxel, the shaders commands [were replaced with the shader UI](https://github.com/lachlanmcdonald/magicavoxel-shaders/wiki/Brush-Shaders).

**Comment by my-little-bunny** [comment]
Hi @lachlanmcdonald, thank you so much for getting back to me. 

Thank you for explaining this about the axis mode. Can I suggest you add this into your shaders descriptions so that the users would know where to look? I myself managed to imitate this with soil3 and rotating my model haha.

I know that the shaders now have shader UI, but the commands still work, and I kind of prefer doing that cause I'm the shortcut kind of person, and manually entering commands for your beautiful shaders gives me pleasure.

Thank you so much for your help & for your outstanding work!

Bunny

**Comment by lachlanmcdonald** [comment]
Hi @my-little-bunny, thanks for the suggestion. I've added a [Terms](https://github.com/lachlanmcdonald/magicavoxel-shaders/wiki/Terms) page that is linked throughout the documentation to explain the Axis Modes.

I've also added the very long [Commands](https://github.com/lachlanmcdonald/magicavoxel-shaders/wiki/Commands) page, which contains a bit more information on how to use the shaders with the console. You will have to compare the documentation with the Commands page to make sense of it, but the arguments have the same name and order on both, so that should help. 🤞
