### ISSUE TITLE
FEAT - Any chance of a 'treemap' shader

### ISSUE THREAD

**Issue by 7bitretro** [lachlanmcdonald/magicavoxel-shaders#22]
I came across this some work by [Dimitris Ladopoulos](http://www.dimitris-ladopoulos.xyz/projects/algorithm.html) and thought a shader to generate Treemap style effects would be awesome and perfect for Magicavoxel.

Example renders from their site.

![algorithm-2](https://user-images.githubusercontent.com/36625634/107794454-63d9e380-6d4f-11eb-9b66-bec2a867bd44.jpg)
![algorithm-11](https://user-images.githubusercontent.com/36625634/107794461-64727a00-6d4f-11eb-8ed8-9601929f24bd.jpg)
![algorithm-4](https://user-images.githubusercontent.com/36625634/107794466-64727a00-6d4f-11eb-837f-b4de6ca2a15f.jpg)

**Comment by lachlanmcdonald** [comment]
I've played with a similar pattern recently, since this technique is useful for greebles. I'll put it on the wish-list for a future release.

**Comment by lachlanmcdonald** [comment]
Hi @7bitretro, turns out this was quite a challenge but I think I have a good implementation of a treemap like pattern. It is not merged yet and there is no documentation, but you can take a look at the pre-release:

https://github.com/lachlanmcdonald/magicavoxel-shaders/blob/feat/treemap/shader/brush/treemap.txt

**Comment by Googyflip** [comment]
Amazing job, thanks!

**Comment by lachlanmcdonald** [comment]
Preparing for 0.12.0 release.
